In [2]:
import csv
import numpy as np

def csv_dict_reader(file_name):
    with open(file_name) as in_file:
        X_train = np.zeros((50, 9))
        X_test = np.zeros((17, 9))
        Y_train = np.zeros((50,1))
        Y_test = np.zeros((17, 1))
        reader = csv.DictReader(in_file)
        i = 0 
        for row in reader:
            if i < 50:
                X_train[i:] = [1,row['lcavol'],row['lweight'],row['age'],row['lbph'],row['svi'],row['lcp'],row['gleason'],row['pgg45']]
                Y_train[i:] = [row['lpsa']]
            else:
                X_test[i-57:] = [1,row['lcavol'],row['lweight'],row['age'],row['lbph'],row['svi'],row['lcp'],row['gleason'],row['pgg45']]
                Y_test[i-50:] = [row['lpsa']]
            i+= 1
    return X_train, X_test, Y_train, Y_test

(X_train, X_test, Y_train, Y_test) = csv_dict_reader('1-prostate-training-data.csv')

In [3]:
I = np.ones((9,9))
for i in range(9):
    for j in range(9):
        if i != j:
            I[i][j]=0
            
print(I)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [4]:
def caculator_w(lamda, A, y):
    B = A.T.dot(A) + I.dot(lamda)
    C = A.T.dot(y)
    w = np.dot(np.linalg.pinv(B), C)
    return w

def test(w, x_test, y_test):
    E = x_test.dot(w)
    F = E - y_test
    Error = 0
    for i in range(F.shape[0]):
        Error += F[i][0]*F[i][0]
    Error = np.sqrt(Error)
    return Error

w = caculator_w(1, X_train, Y_train)
print(w)
error = test(w, X_test, Y_test)
print(error)

[[-0.11540857]
 [ 0.44791717]
 [ 0.52839008]
 [-0.01150637]
 [ 0.15199873]
 [ 0.12093811]
 [-0.04198446]
 [ 0.06854118]
 [ 0.00539167]]
3.62041143863


In [5]:
lamda = 0.001
w = caculator_w(lamda, X_train, Y_train)
error2 = error1 = test(w,X_test,Y_test)
    
for i in range(1000):
    lamda += 0.01
    w = w = caculator_w(lamda, X_train, Y_train)
    error2 = test(w,X_test,Y_test)
    print(error, error2-error1)
    if error2-error1 < 0:
        print(lamda)
    error1 = error2

3.62041143863 -0.00547250017193
0.011
3.62041143863 -0.00478431357947
0.020999999999999998
3.62041143863 -0.00419446311388
0.031
3.62041143863 -0.00368515688045
0.041
3.62041143863 -0.00324245043098
0.051000000000000004
3.62041143863 -0.00285529007688
0.061000000000000006
3.62041143863 -0.00251482261811
0.07100000000000001
3.62041143863 -0.00221388997402
0.081
3.62041143863 -0.00194665416738
0.091
3.62041143863 -0.00170831566004
0.10099999999999999
3.62041143863 -0.00149489936783
0.11099999999999999
3.62041143863 -0.00130309040086
0.12099999999999998
3.62041143863 -0.00113010675129
0.13099999999999998
3.62041143863 -0.000973599735671
0.141
3.62041143863 -0.000831575452787
0.151
3.62041143863 -0.000702332390271
0.161
3.62041143863 -0.000584411443206
0.171
3.62041143863 -0.000476555638484
0.18100000000000002
3.62041143863 -0.000377677442131
0.19100000000000003
3.62041143863 -0.000286832084637
0.20100000000000004
3.62041143863 -0.000203195644796
0.21100000000000005
3.62041143863 -0.000126

3.62041143863 0.000694924319732
3.62041143863 0.000694269337456
3.62041143863 0.000693615474312
3.62041143863 0.000692962725841
3.62041143863 0.000692311090822
3.62041143863 0.000691660566232
3.62041143863 0.000691011148344
3.62041143863 0.000690362836103
3.62041143863 0.000689715624938
3.62041143863 0.000689069514711
3.62041143863 0.000688424500756
3.62041143863 0.000687780580961
3.62041143863 0.000687137753149
3.62041143863 0.000686496014094
3.62041143863 0.000685855361914
3.62041143863 0.000685215793687
3.62041143863 0.000684577306096
3.62041143863 0.000683939897419
3.62041143863 0.000683303564692
3.62041143863 0.000682668306033
3.62041143863 0.000682034117482
3.62041143863 0.000681400997812
3.62041143863 0.000680768943907
3.62041143863 0.000680137952986
3.62041143863 0.000679508022884
3.62041143863 0.000678879151102
3.62041143863 0.00067825133437
3.62041143863 0.000677624571757
3.62041143863 0.000676998858513
3.62041143863 0.000676374193749
3.62041143863 0.000675750574568
3.6204114

3.62041143863 0.000476041210009
3.62041143863 0.000475709604016
3.62041143863 0.000475378407157
3.62041143863 0.000475047619479
3.62041143863 0.000474717239036
3.62041143863 0.000474387266504
3.62041143863 0.000474057699827
3.62041143863 0.000473728539149
3.62041143863 0.000473399782756
3.62041143863 0.000473071431735
3.62041143863 0.000472743483219
3.62041143863 0.000472415937656
3.62041143863 0.000472088794369
3.62041143863 0.000471762052196
3.62041143863 0.000471435710492
3.62041143863 0.000471109768507
3.62041143863 0.000470784225587


In [6]:
import csv
def csv_dict_reader2(file_name):
    with open(file_name) as in_file:
        X = np.zeros((10, 9))
        reader = csv.DictReader(in_file)
        i = 0
        for row in reader:
            X[i:] = [1,row['lcavol'],row['lweight'],row['age'],row['lbph'],row['svi'],row['lcp'],row['gleason'],row['pgg45']]    
            i+=1
    return X
w = caculator_w(0.231, X_train, Y_train)
X = csv_dict_reader2('1-prostate-test-Vi-Du.csv')
print(X)
E = X.dot(w)
print(E)

[[  1.          -0.9818495    2.169459    51.          -1.629436     0.
   -1.38629436   6.           0.        ]
 [  1.          -0.99425227   3.319626    58.          -1.38629436   0.
   -1.38629436   6.           0.        ]
 [  1.           1.25         2.691243    74.          -1.38629436   0.
   -1.38629436   7.          20.        ]
 [  1.          -1.2039728    3.282789    58.          -1.38629436   0.
   -1.38629436   6.           0.        ]
 [  1.           0.75141609   3.432373    62.          -1.629436     0.
   -1.38629436   6.           0.        ]
 [  1.          -1.9822124    3.228826    50.          -1.38629436   0.
   -1.38629436   6.           0.        ]
 [  1.           0.69314718   3.539509    58.           1.3686722    0.
   -1.38629436   6.           0.        ]
 [  1.           0.2642218    3.6138      65.          -1.38629436   0.
   -1.38629436   6.           0.        ]
 [  1.          -1.34707365   3.598681    63.           1.2669476    0.
   -1.38629436  