In [1]:
mydoclist = ['Julie loves me more than Linda loves me',
'Jane likes me more than Julie loves me',
'He likes basketball more than baseball']

#mydoclist = ['sun sky bright', 'sun sun bright']

from collections import Counter

for doc in mydoclist:
    tf = Counter()
    for word in doc.split():
        tf[word] +=1
    print(tf.items())

dict_items([('Julie', 1), ('loves', 2), ('me', 2), ('more', 1), ('than', 1), ('Linda', 1)])
dict_items([('Jane', 1), ('likes', 1), ('me', 2), ('more', 1), ('than', 1), ('Julie', 1), ('loves', 1)])
dict_items([('He', 1), ('likes', 1), ('basketball', 1), ('more', 1), ('than', 1), ('baseball', 1)])


In [2]:
import string #allows for format()
    
def build_lexicon(corpus):
    lexicon = set()
    for doc in corpus:
        lexicon.update([word for word in doc.split()])
    return lexicon

def tf(term, document):
  return freq(term, document)

def freq(term, document):
  return document.split().count(term)

vocabulary = build_lexicon(mydoclist)

doc_term_matrix = []
print('Our vocabulary vector is [' + ', '.join(list(vocabulary)) + ']')
for doc in mydoclist:
    print('The doc is "' + doc + '"')
    tf_vector = [tf(word, doc) for word in vocabulary]
    tf_vector_string = ', '.join(format(freq, 'd') for freq in tf_vector)
    print('The tf vector for Document %d is [%s]' % ((mydoclist.index(doc)+1), tf_vector_string))
    doc_term_matrix.append(tf_vector)
    
    # here's a test: why did I wrap mydoclist.index(doc)+1 in parens?  it returns an int...
    # try it!  type(mydoclist.index(doc) + 1)

print('All combined, here is our master document term matrix: ')
print(doc_term_matrix)

Our vocabulary vector is [basketball, me, He, more, Julie, than, Linda, likes, baseball, Jane, loves]
The doc is "Julie loves me more than Linda loves me"
The tf vector for Document 1 is [0, 2, 0, 1, 1, 1, 1, 0, 0, 0, 2]
The doc is "Jane likes me more than Julie loves me"
The tf vector for Document 2 is [0, 2, 0, 1, 1, 1, 0, 1, 0, 1, 1]
The doc is "He likes basketball more than baseball"
The tf vector for Document 3 is [1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0]
All combined, here is our master document term matrix: 
[[0, 2, 0, 1, 1, 1, 1, 0, 0, 0, 2], [0, 2, 0, 1, 1, 1, 0, 1, 0, 1, 1], [1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0]]


In [3]:
import math
import numpy as np

def l2_normalizer(vec):
    denom = np.sum([el**2 for el in vec])
    return [(el / math.sqrt(denom)) for el in vec]

doc_term_matrix_l2 = []
for vec in doc_term_matrix:
    doc_term_matrix_l2.append(l2_normalizer(vec))

print('A regular old document term matrix: ') 
print(np.matrix(doc_term_matrix))
print('\nA document term matrix with row-wise L2 norms of 1:')
print(np.matrix(doc_term_matrix_l2))

# if you want to check this math, perform the following:
# from numpy import linalg as la
# la.norm(doc_term_matrix[0])
# la.norm(doc_term_matrix_l2[0])

A regular old document term matrix: 
[[0 2 0 1 1 1 1 0 0 0 2]
 [0 2 0 1 1 1 0 1 0 1 1]
 [1 0 1 1 0 1 0 1 1 0 0]]

A document term matrix with row-wise L2 norms of 1:
[[ 0.          0.57735027  0.          0.28867513  0.28867513  0.28867513
   0.28867513  0.          0.          0.          0.57735027]
 [ 0.          0.63245553  0.          0.31622777  0.31622777  0.31622777
   0.          0.31622777  0.          0.31622777  0.31622777]
 [ 0.40824829  0.          0.40824829  0.40824829  0.          0.40824829
   0.          0.40824829  0.40824829  0.          0.        ]]


In [1]:
def numDocsContaining(word, doclist):
    doccount = 0
    for doc in doclist:
        if freq(word, doc) > 0:
            doccount +=1
    return doccount 

def idf(word, doclist):
    n_samples = len(doclist)
    df = numDocsContaining(word, doclist)
    return np.log(n_samples / 1+df)

my_idf_vector = [idf(word, mydoclist) for word in vocabulary]

print('Our vocabulary vector is [' + ', '.join(list(vocabulary)) + ']')
print('The inverse document frequency vector is [' + ', '.join(format(freq, 'f') for freq in my_idf_vector) + ']')

NameError: name 'vocabulary' is not defined

In [11]:
np.log(3)

1.0986122886681098

In [12]:
import numpy as np
A =np.matrix('0, 0, 0; 1, 0, 1; 1, 0, 1')
W = np.matrix('1,1,1;1,0,0;-1,-1,0')
C = np.sum(A*W)
print(C)

2


In [13]:
import numpy as np
A =np.matrix('0, 0, 0; 2, 0, 2; 0, 0, 2')
W = np.matrix('0,0,0;-1,-1,1;1,1,1')
C = np.sum(A.dot(W))
print(C)

12


In [14]:
import numpy as np
A =np.matrix('0, 0, 0; 1, 2, 1; 0, 0, 2')
W = np.matrix('0,0,-1;0,1,-1;0,1,0')
C = np.sum(A.dot(W))
print(C)

2
